import type { Metadata } from "next";
import { Geist, Geist_Mono, } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/toast-1";
import ShowNavbarAndFooter from "@/components/shared/ShowNavbarAndFooter";
import QueryProvider from "@/providers/QueryProvider";
import { ThemeProvider } from "next-themes"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      ><QueryProvider>
          <ThemeProvider
            attribute={'class'}
            enableSystem
            defaultTheme="system"
          >
            <ShowNavbarAndFooter>
              <ToastProvider>
                {children}
              </ToastProvider>
            </ShowNavbarAndFooter>
          </ThemeProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
